/* ─────────────────────────────────────────────────────────────────────────────
   ReportCard Component
   Renders the structured FINDINGS / IMPRESSION / RECOMMENDATION report
───────────────────────────────────────────────────────────────────────────── */

import { useState } from 'react';
import { Copy, Check, Download, FileText } from 'lucide-react';
import SeverityBadge from './SeverityBadge';

export default function ReportCard({ report, tumorClass, confidence, severity, patientAge, patientSex }) {
  const [copied, setCopied] = useState(false);

  if (!report) return null;

  const classLabel = tumorClass
    ? tumorClass.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
    : '';

  const fullText = `BRAIN TUMOUR MRI REPORT
${'='.repeat(52)}
Classification : ${classLabel}
Confidence     : ${(confidence * 100).toFixed(1)}%
Severity Grade : ${severity}
${patientAge ? `Patient Age    : ${patientAge}` : ''}
${patientSex ? `Patient Sex    : ${patientSex}` : ''}

FINDINGS:
${report.findings || 'N/A'}

IMPRESSION:
${report.impression || 'N/A'}

RECOMMENDATION:
${report.recommendation || 'N/A'}

${'─'.repeat(52)}
Generated by NeuroScan AI — Project 22ADP72
Kongu Engineering College | B.E. AI & DS 2027
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(fullText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([fullText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `brain_tumour_report_${tumorClass}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="glass-card" style={{ padding: '24px' }}>
      {/* Header */}
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'flex-start',
          marginBottom: '20px',
          flexWrap: 'wrap',
          gap: '12px',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <FileText size={20} color="var(--color-cyan)" />
          <h3 style={{ fontSize: '1.05rem', color: 'var(--text-primary)' }}>
            Radiology Report
          </h3>
        </div>

        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
          <SeverityBadge severity={severity} size="sm" />

          <button className="btn-ghost" onClick={handleCopy} style={{ fontSize: '0.78rem' }}>
            {copied ? <Check size={13} color="var(--sev-mild)" /> : <Copy size={13} />}
            {copied ? 'Copied!' : 'Copy'}
          </button>

          <button className="btn-secondary" onClick={handleDownload} style={{ fontSize: '0.8rem', padding: '6px 14px' }}>
            <Download size={13} />
            Download
          </button>
        </div>
      </div>

      {/* Meta line */}
      <div
        style={{
          fontSize: '0.78rem',
          color: 'var(--text-muted)',
          marginBottom: '20px',
          padding: '8px 12px',
          background: 'rgba(255,255,255,0.03)',
          borderRadius: '8px',
          display: 'flex',
          gap: '20px',
          flexWrap: 'wrap',
        }}
      >
        <span>Classification: <strong style={{ color: 'var(--text-secondary)' }}>{classLabel}</strong></span>
        <span>Confidence: <strong style={{ color: 'var(--text-secondary)' }}>{(confidence * 100).toFixed(1)}%</strong></span>
        {patientAge && <span>Age: <strong style={{ color: 'var(--text-secondary)' }}>{patientAge}</strong></span>}
        {patientSex && <span>Sex: <strong style={{ color: 'var(--text-secondary)' }}>{patientSex}</strong></span>}
        {report.llm_used && (
          <span>
            Generated by:{' '}
            <strong style={{ color: report.llm_used === 'ollama' ? 'var(--color-cyan)' : 'var(--text-muted)' }}>
              {report.llm_used === 'ollama' ? '🤖 Ollama LLM' : '📋 Clinical Template'}
            </strong>
          </span>
        )}
      </div>

      {/* Sections */}
      <ReportSection
        label="🔬 Findings"
        text={report.findings}
        colorClass="report-section-findings"
        labelColor="var(--color-cyan)"
      />
      <ReportSection
        label="🩺 Impression"
        text={report.impression}
        colorClass="report-section-impression"
        labelColor="var(--color-purple)"
      />
      <ReportSection
        label="💊 Recommendation"
        text={report.recommendation}
        colorClass="report-section-rec"
        labelColor="var(--color-teal)"
        isLast
      />
    </div>
  );
}

function ReportSection({ label, text, colorClass, labelColor, isLast }) {
  return (
    <div
      className={`report-section ${colorClass}`}
      style={{ marginBottom: isLast ? 0 : '16px' }}
    >
      <div className="report-section-label" style={{ color: labelColor }}>
        {label}
      </div>
      <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', lineHeight: '1.7' }}>
        {text || 'No content available.'}
      </p>
    </div>
  );
}
