/* ─────────────────────────────────────────────────────────────────────────────
   Home Page — Hero + Features + Stats + CTA
───────────────────────────────────────────────────────────────────────────── */

import { useNavigate } from 'react-router-dom';
import {
  Brain, Zap, Shield, FileText, ChevronRight,
  TrendingUp, Activity, Award
} from 'lucide-react';

const FEATURES = [
  {
    icon: Brain,
    color: '#6366f1',
    title: '3-Model Ensemble',
    desc: 'Combines EfficientNet-B4, DenseNet-121, and ResNet-50 for higher accuracy and robustness.',
  },
  {
    icon: Zap,
    color: '#06b6d4',
    title: 'Instant Classification',
    desc: 'Real-time classification with CLAHE preprocessing, ROI extraction, and gamma correction pipeline.',
  },
  {
    icon: TrendingUp,
    color: '#8b5cf6',
    title: 'Severity Grading',
    desc: 'Confidence-grounded severity grading (Mild / Moderate / Severe) based on validated clinical rules.',
  },
  {
    icon: FileText,
    color: '#0d9488',
    title: 'LLM Report Generation',
    desc: 'Structured radiology reports (Findings / Impression / Recommendation) generated by local Ollama LLM.',
  },
  {
    icon: Shield,
    color: '#ec4899',
    title: 'Anti-Hallucination',
    desc: 'CNN classifier output is used as a hard grounding constraint, significantly reducing LLM hallucination.',
  },
  {
    icon: Award,
    color: '#f59e0b',
    title: 'NLP Evaluation',
    desc: 'BLEU-1, ROUGE-L, and BERTScore metrics to evaluate report quality against reference reports.',
  },
];

const CLASSES = [
  { name: 'Glioma',       emoji: '🧬', images: '1,621', color: '#6366f1' },
  { name: 'Meningioma',   emoji: '🔬', images: '1,645', color: '#8b5cf6' },
  { name: 'Pituitary',    emoji: '🫀', images: '1,757', color: '#06b6d4' },
  { name: 'No Tumour',    emoji: '✅', images: '2,000', color: '#22c55e' },
  { name: 'Metastasis',   emoji: '🦠', images: '~2,800',  color: '#f59e0b' },
  { name: 'Pediatric Glioma', emoji: '🧒', images: '~1,200',  color: '#ec4899' },
];

const STATS = [
  { value: '6',      label: 'Tumour Classes', icon: Brain },
  { value: '7,000+', label: 'Training Images', icon: Activity },
  { value: 'Ens',    label: 'Ensemble',       icon: Zap },
  { value: '3',      label: 'NLP Metrics',    icon: Award },
];

export default function Home() {
  const navigate = useNavigate();

  return (
    <div style={{ padding: '60px 0 100px' }}>
      <div className="container">


        {/* ── Stats ────────────────────────────────────────── */}
        <div className="grid-4" style={{ marginBottom: '80px' }}>
          {STATS.map(({ value, label, icon: Icon }) => (
            <div key={label} className="glass-card metric-card" style={{ padding: '28px 20px' }}>
              <div className="metric-value gradient-text">{value}</div>
              <div className="metric-label">{label}</div>
            </div>
          ))}
        </div>

        {/* ── Disease Classes ───────────────────────────────── */}
        <div style={{ marginBottom: '80px' }}>
          <div style={{ textAlign: 'center', marginBottom: '40px' }}>
            <h2 style={{ fontSize: '2rem', marginBottom: '12px' }}>
              6-Class <span className="gradient-text">Disease Coverage</span>
            </h2>
            <p style={{ color: 'var(--text-muted)', maxWidth: 500, margin: '0 auto' }}>
              Comprehensive multi-class detection spanning the most clinically significant brain tumour types.
            </p>
          </div>

          <div className="grid-3">
            {CLASSES.map(({ name, emoji, images, color }) => (
              <div
                key={name}
                className="glass-card"
                style={{
                  padding: '24px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '16px',
                  cursor: 'default',
                }}
              >
                <div
                  style={{
                    width: 48,
                    height: 48,
                    borderRadius: '12px',
                    background: `${color}22`,
                    border: `1px solid ${color}44`,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: '22px',
                    flexShrink: 0,
                  }}
                >
                  {emoji}
                </div>
                <div>
                  <div style={{ fontWeight: 600, fontSize: '0.95rem', color: 'var(--text-primary)', marginBottom: '4px' }}>
                    {name}
                  </div>
                  <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>
                    {images} training images
                  </div>
                </div>
                <div
                  style={{
                    marginLeft: 'auto',
                    width: 8,
                    height: 8,
                    borderRadius: '50%',
                    background: color,
                    boxShadow: `0 0 8px ${color}`,
                    flexShrink: 0,
                  }}
                />
              </div>
            ))}
          </div>
        </div>

        {/* ── Feature Cards ────────────────────────────────── */}
        <div style={{ marginBottom: '80px' }}>
          <div style={{ textAlign: 'center', marginBottom: '40px' }}>
            <h2 style={{ fontSize: '2rem', marginBottom: '12px' }}>
              System <span className="gradient-text">Architecture</span>
            </h2>
            <p style={{ color: 'var(--text-muted)', maxWidth: 500, margin: '0 auto' }}>
              Novel combination of CNN classification and LLM report generation with hard grounding constraints.
            </p>
          </div>

          <div className="grid-3">
            {FEATURES.map(({ icon: Icon, color, title, desc }) => (
              <div key={title} className="glass-card" style={{ padding: '28px' }}>
                <div
                  style={{
                    width: 44,
                    height: 44,
                    borderRadius: '12px',
                    background: `${color}20`,
                    border: `1px solid ${color}40`,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    marginBottom: '16px',
                  }}
                >
                  <Icon size={20} color={color} />
                </div>
                <h3 style={{ fontSize: '0.95rem', fontWeight: 600, marginBottom: '8px', color: 'var(--text-primary)' }}>
                  {title}
                </h3>
                <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', lineHeight: 1.65 }}>
                  {desc}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* ── CTA Banner ───────────────────────────────────── */}
        <div
          style={{
            background: 'var(--grad-glow)',
            border: '1px solid rgba(99,102,241,0.25)',
            borderRadius: 'var(--radius-xl)',
            padding: '48px 40px',
            textAlign: 'center',
          }}
        >
          <h2 style={{ fontSize: '2rem', marginBottom: '12px' }}>
            Ready to Analyse?
          </h2>
          <p style={{ color: 'var(--text-secondary)', marginBottom: '28px', maxWidth: 480, margin: '0 auto 28px' }}>
            Upload a brain MRI scan and receive an instant AI-powered radiology report in seconds.
          </p>
          <button className="btn-primary pulse-glow" style={{ fontSize: '1rem', padding: '14px 36px' }} onClick={() => navigate('/analyze')}>
            <Brain size={18} />
            Start Analysis
            <ChevronRight size={16} />
          </button>
        </div>

      </div>
    </div>
  );
}
